name: Build and Release Butler

on:
  push:
    tags:
      - "v*" # e.g. v1.0.0
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-proto:
    name: Generate Proto Files
    runs-on: ubuntu-latest
    env:
      ACT: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run proto-generator container
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/tonalflex/elk-audio-os-builder:latest
          options: --platform linux/amd64 --user root -v ${{ github.workspace }}:/workspace -w /workspace
          run: ./script/generate-proto.sh

      - name: Upload generated proto files
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: proto-files
          path: ./proto # adjust path to wherever your generated files live

  build-binary:
    name: Build Linux ARM64 Binary
    needs: generate-proto
    runs-on: ubuntu-latest
    env:
      ACT: false
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download proto files to a temp dir
        if: ${{ !env.ACT }}
        uses: actions/download-artifact@v4
        with:
          name: proto-files
          path: ./downloaded-proto

      - name: Replace ./proto with downloaded files
        run: |
          rm -rf ./proto
          mkdir -p ./proto
          cp -r ./downloaded-proto/* ./proto/

      - name: Confirm generated proto files are present
        run: |
          echo "Listing ./proto contents:"
          ls -lah ./proto
          echo
          echo "Previewing one .py file (if any):"
          head -n 10 ./proto/*_pb2.py || echo "No *_pb2.py files found"

      - name: Run QEMU builder container
        uses: addnab/docker-run-action@v3
        with:
          image: python:3.12.10-slim-bullseye
          options: --platform linux/arm64 -v ${{ github.workspace }}:/workspace -w /workspace --entrypoint ""
          run: ./script/build.sh

      - name: Package binary as tar.gz
        run: |
          mkdir -p release
          cp dist/butler release/
          tar -czvf butler-${{ github.ref_name }}-linux-arm64.tar.gz -C release butler
          cp butler-${{ github.ref_name }}-linux-arm64.tar.gz butler-linux-arm64.tar.gz

      - name: Upload binary to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            butler-${{ github.ref_name }}-linux-arm64.tar.gz
            butler-linux-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
